---
abstract: 'Manage ruby versions'
author:
  - 'mugen Kenichi <mugen.kenichi@uninets.eu>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ruby-VersionManager
no_index:
  directory:
    - t
provides:
  Ruby::VersionManager:
    file: lib/Ruby/VersionManager.pm
    version: 0.003014
  Ruby::VersionManager::Config:
    file: lib/Ruby/VersionManager/Config.pm
    version: 0.003014
  Ruby::VersionManager::Version:
    file: lib/Ruby/VersionManager/Version.pm
    version: 0.003014
requires:
  Cwd: 0
  File::Path: 0
  LWP: 0
  LWP::Simple: 0
  Moo: 0
  YAML: 0
  autodie: 0
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.003014
